service: serverless-go-github-lang-rate

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 3600

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  get:
    handler: bin/get
    timeout: 60
    events:
      - http:
          path: /get
          method: get
          caching:
            enabled: true
    environment:
      GITHUB_USERNAME: ${env:GITHUB_USERNAME}
